theme: jekyll-theme-cayman
title: HarvestX
description: Platform analisis harga pangan berbasis AI yang menyediakan data harga harian, histori harga, prediksi tren, dan simulasi belanja untuk membantu perencanaan keuangan dan strategi bisnis.
