name: Test

on: 
    push: 
        branches: [main]

jobs:
    test-build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Print Hello World
              run: echo "Hello, GitHub Actions!"
            - name: List Files in Repo
              run: ls -la
